### ISSUE TITLE
PHP 7 Error Handling

### ISSUE THREAD

**Issue by Nilithus** [quickenloans-mcp/mcp-panthor#8]
Certain errors in PHP 7 are now [error objects](https://secure.php.net/manual/en/language.errors.php7.php) that implement throwable and don't extend exception. If you are trying to use php 7 with mcp-panthor and you have a parser error or something that throws an `Error` object the issue will be obfuscated because `QL\Panthor\ErrorHandling\ErrorHandler::handleException` type hints on `Exception`

You'll end up with Error messages like this:
![screen shot 2016-03-15 at 10 28 15 pm](https://cloud.githubusercontent.com/assets/1783861/13800189/466415fc-eafd-11e5-988f-f56ccbdfe3db.png)

Obviously people can write their own exception handler for this but might be nice if mcp-panthor came with one by default.

**Comment by Nilithus** [comment]
Hmmm the [ExceptionHandlerInterface](https://github.com/quickenloans-mcp/mcp-panthor/blob/master/src/ErrorHandling/ExceptionHandlerInterface.php#L28) typehints on `Exception` which is problematic. Ideally it'd type hint on `Throwable` since that is the new generic thing linking Exceptions and Error objects but that would only work if you are running php7 which is no good for BC :-1:

**Comment by skluck** [comment]
Fixed in https://github.com/quickenloans-mcp/mcp-panthor/commit/4ab6a2964024725ddbb1e9de1166aa2e1d21b175 - will release as 2.4 soon.

**Comment by skluck** [comment]
2.4 is now released with this change.

[2.4 release notes](/quickenloans-mcp/mcp-panthor/releases/tag/2.4.0)
